# Server configuration
server.ws.url=ws://192.168.50.22:8080/ws/agent
server.auth.url=http://192.168.50.22:8080/auth/login

# Agent configuration
pc.name=MyJavaAgent

# Auth credentials
auth.username=testuser
auth.password=12345