# Server configuration
server.ws.url=ws://192.168.50.22:8080/ws/agent
server.auth.url=http://192.168.50.22:8080/auth/login

# Agent configuration
pc.name=PC2

# Auth credentials
auth.username=testuser
auth.password=12345

# Video
video.enabled=true
video.public.url=http://192.168.50.32:8000
video.stream.name=desktop

# GStreamer
gst.launch.path=C:/gstreamer/1.0/msvc_x86_64/bin/gst-launch-1.0.exe
gstreamer.http.port=8000
gstreamer.webrtc.port=8443
gstreamer.width=1280
gstreamer.height=720
gstreamer.fps=30

